spring:
  profiles:
    active: ${PROFILE_ACTIVE:local}
  application:
    name: ps-customer-service
  cloud:
    config:
      fail-fast: true
    stream:
      bindings:
        fromPaymentService-in-0:
          destination: executionPayment
          content-type: application/json
          group: ${spring.application.name}
        toNotificationService-out-0:
          destination: toNotify
          content-type: application/json
      rabbit:
        bindings:
          fromPaymentService-in-0:
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true
              transacted: true
          toNotificationService-out-0:
            producer:
              transacted: true

logging:
  level:
    com.lucasmoraist: ${LOG_LEVEL:DEBUG}

app:
  security-ignore:
    actuatorHealth: /actuator/health
    actuatorLiveness: /actuator/health/liveness
    actuatorReadiness: /actuator/health/readiness